[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sardis_agent_wallet = "HUWhjAJUk6mf8ikxd2PDSdYGzLbdbA6ZPX7p4XZRVLpP"

[programs.localnet]
sardis_agent_wallet = "5shhNxoGDhGe7XotwG5usrZ21K5mZdj3q2oGZC7cYpvN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "/Users/efebarandurmaz/sardis/packages/sardis-solana-program/run-tests.sh"
