"""Core domain primitives shared across Sardis services."""

from .exceptions import (
    SardisException,
    SardisValidationError,
    SardisNotFoundError,
    SardisAuthenticationError,
    SardisAuthorizationError,
    SardisConflictError,
    SardisPaymentError,
    SardisPolicyViolationError,
    SardisInsufficientBalanceError,
    SardisTransactionFailedError,
    SardisMandateError,
    SardisSignatureError,
    SardisMandateExpiredError,
    SardisMandateReplayError,
    SardisMandateChainError,
    SardisChainError,
    SardisRPCError,
    SardisDatabaseError,
    SardisMPCError,
    SardisComplianceError,
    SardisKYCRequiredError,
    SardisKYCExpiredError,
    SardisSanctionsHitError,
    SardisTravelRuleError,
    SardisAlgorithmNotSupportedError,
    SardisHoldError,
    SardisHoldNotFoundError,
    SardisHoldExpiredError,
    SardisHoldAlreadyCapturedError,
    SardisHoldAlreadyVoidedError,
    SardisConfigurationError,
    SardisDependencyNotConfiguredError,
    SardisRateLimitError,
)
from .config import SardisSettings, load_settings, TurnkeyConfig, MPCProvider, ChainConfig
from .identity import AgentIdentity
from .mandates import IntentMandate, CartMandate, PaymentMandate, MandateChain
from .tokens import TokenType, TokenMetadata
from .wallets import Wallet, TokenLimit, TokenBalance  # TokenBalance is alias for TokenLimit
from .spending_policy import SpendingPolicy, TimeWindowLimit, MerchantRule, TrustLevel, SpendingScope, create_default_policy
from .transactions import Transaction, TransactionStatus, OnChainRecord
from .virtual_card import VirtualCard, CardStatus, CardType, FundingSource
from .orchestrator import PaymentOrchestrator, PaymentResult, PaymentExecutionError
from .database import Database, init_database, SCHEMA_SQL
from .holds import Hold, HoldResult, HoldsRepository
from .webhooks import (
    EventType,
    WebhookEvent,
    WebhookSubscription,
    DeliveryAttempt,
    WebhookRepository,
    WebhookService,
    create_payment_event,
    create_hold_event,
)
from .cache import CacheService, CacheBackend, InMemoryCache, RedisCache, create_cache_service
from .agents import Agent, AgentPolicy, SpendingLimits, AgentRepository
from .wallet_repository import WalletRepository

__all__ = [
    # Exceptions
    "SardisException",
    "SardisValidationError",
    "SardisNotFoundError",
    "SardisAuthenticationError",
    "SardisAuthorizationError",
    "SardisConflictError",
    "SardisPaymentError",
    "SardisPolicyViolationError",
    "SardisInsufficientBalanceError",
    "SardisTransactionFailedError",
    "SardisMandateError",
    "SardisSignatureError",
    "SardisMandateExpiredError",
    "SardisMandateReplayError",
    "SardisMandateChainError",
    "SardisChainError",
    "SardisRPCError",
    "SardisDatabaseError",
    "SardisMPCError",
    "SardisComplianceError",
    "SardisKYCRequiredError",
    "SardisKYCExpiredError",
    "SardisSanctionsHitError",
    "SardisTravelRuleError",
    "SardisAlgorithmNotSupportedError",
    "SardisHoldError",
    "SardisHoldNotFoundError",
    "SardisHoldExpiredError",
    "SardisHoldAlreadyCapturedError",
    "SardisHoldAlreadyVoidedError",
    "SardisConfigurationError",
    "SardisDependencyNotConfiguredError",
    "SardisRateLimitError",
    # Config
    "SardisSettings",
    "TurnkeyConfig",
    "MPCProvider",
    "ChainConfig",
    "AgentIdentity",
    "IntentMandate",
    "CartMandate",
    "PaymentMandate",
    "MandateChain",
    "load_settings",
    "TokenType",
    "TokenMetadata",
    "Wallet",
    "TokenLimit",
    "TokenBalance",  # Backwards compatibility alias for TokenLimit
    "SpendingPolicy",
    "TimeWindowLimit",
    "MerchantRule",
    "TrustLevel",
    "SpendingScope",
    "create_default_policy",
    "Transaction",
    "TransactionStatus",
    "OnChainRecord",
    "VirtualCard",
    "CardStatus",
    "CardType",
    "FundingSource",
    "PaymentOrchestrator",
    "PaymentResult",
    "PaymentExecutionError",
    "Database",
    "init_database",
    "SCHEMA_SQL",
    "Hold",
    "HoldResult",
    "HoldsRepository",
    "EventType",
    "WebhookEvent",
    "WebhookSubscription",
    "DeliveryAttempt",
    "WebhookRepository",
    "WebhookService",
    "create_payment_event",
    "create_hold_event",
    "CacheService",
    "CacheBackend",
    "InMemoryCache",
    "RedisCache",
    "create_cache_service",
    "Agent",
    "AgentPolicy",
    "SpendingLimits",
    "AgentRepository",
    "WalletRepository",
]
