"""Initial migration

Revision ID: 32e8602c473e
Revises: 
Create Date: 2025-12-01 21:23:50.014924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e8602c473e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('admin_ids', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('transactions',
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('from_wallet', sa.String(), nullable=False),
    sa.Column('to_wallet', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tx_id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_from_wallet'), 'transactions', ['from_wallet'], unique=False)
    op.create_index(op.f('ix_transactions_to_wallet'), 'transactions', ['to_wallet'], unique=False)
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wallet_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('wallets',
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('balances', sa.JSON(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('limit_per_tx', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('limit_total', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('spent_total', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('virtual_card', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_table('agents')
    op.drop_index(op.f('ix_transactions_to_wallet'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_wallet'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
