import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  createMint,
  createAssociatedTokenAccount,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  getAccount,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { expect } from "chai";

// IDL type will be generated by anchor build
type SardisAgentWallet = any;

describe("sardis_agent_wallet", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace
    .SardisAgentWallet as Program<SardisAgentWallet>;

  // Test keypairs
  const authority = provider.wallet as anchor.Wallet;
  const owner = Keypair.generate();
  const coSigner = Keypair.generate();
  const merchant = Keypair.generate();
  const unauthorizedUser = Keypair.generate();

  let mint: PublicKey;
  let secondMint: PublicKey;
  let walletPda: PublicKey;
  let walletBump: number;
  let merchantRegistryPda: PublicKey;
  let tokenAllowlistPda: PublicKey;
  let sourceAta: PublicKey;
  let destinationAta: PublicKey;

  const USDC_DECIMALS = 6;
  const ONE_USDC = 1_000_000; // 1 USDC in minor units

  before(async () => {
    // Airdrop SOL to authority
    const sig = await provider.connection.requestAirdrop(
      authority.publicKey,
      10 * LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(sig);

    // Airdrop SOL to co-signer for signing transactions
    const sig2 = await provider.connection.requestAirdrop(
      coSigner.publicKey,
      2 * LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(sig2);

    // Derive wallet PDA
    [walletPda, walletBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("sardis_wallet"), owner.publicKey.toBuffer()],
      program.programId
    );

    // Derive merchant registry PDA
    [merchantRegistryPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("merchants"), walletPda.toBuffer()],
      program.programId
    );

    // Derive token allowlist PDA
    [tokenAllowlistPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("tokens"), walletPda.toBuffer()],
      program.programId
    );

    // Create mock USDC mint
    mint = await createMint(
      provider.connection,
      (authority as any).payer,
      authority.publicKey,
      null,
      USDC_DECIMALS
    );

    // Create second mint for token allowlist tests
    secondMint = await createMint(
      provider.connection,
      (authority as any).payer,
      authority.publicKey,
      null,
      USDC_DECIMALS
    );
  });

  describe("initialize_wallet", () => {
    it("creates wallet with correct policy parameters", async () => {
      // Step 1: Create wallet PDA
      await program.methods
        .initializeWallet({
          trustLevel: 1, // MEDIUM
          limitPerTx: new anchor.BN(500 * ONE_USDC),
          limitTotal: new anchor.BN(100_000 * ONE_USDC),
          dailyLimit: new anchor.BN(5_000 * ONE_USDC),
          weeklyLimit: new anchor.BN(25_000 * ONE_USDC),
          monthlyLimit: new anchor.BN(50_000 * ONE_USDC),
          cosignLimitPerTx: new anchor.BN(5_000 * ONE_USDC),
          cosignDailyLimit: new anchor.BN(50_000 * ONE_USDC),
          coSigner: coSigner.publicKey,
        })
        .accounts({
          owner: owner.publicKey,
          authority: authority.publicKey,
          wallet: walletPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // Step 2: Create merchant registry + token allowlist PDAs
      await program.methods
        .initializeRegistries()
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
          tokenAllowlist: tokenAllowlistPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const wallet = await program.account.agentWallet.fetch(walletPda);
      expect(wallet.owner.toBase58()).to.equal(owner.publicKey.toBase58());
      expect(wallet.authority.toBase58()).to.equal(
        authority.publicKey.toBase58()
      );
      expect(wallet.trustLevel).to.equal(1);
      expect(wallet.limitPerTx.toNumber()).to.equal(500 * ONE_USDC);
      expect(wallet.dailyLimit.toNumber()).to.equal(5_000 * ONE_USDC);
      expect(wallet.weeklyLimit.toNumber()).to.equal(25_000 * ONE_USDC);
      expect(wallet.monthlyLimit.toNumber()).to.equal(50_000 * ONE_USDC);
      expect(wallet.paused).to.equal(0);
      expect(wallet.useAllowlist).to.equal(0);
      expect(wallet.enforceTokenAllowlist).to.equal(0);
    });

    it("rejects invalid trust level", async () => {
      const badOwner = Keypair.generate();
      const [badWalletPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("sardis_wallet"), badOwner.publicKey.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .initializeWallet({
            trustLevel: 5, // Invalid
            limitPerTx: new anchor.BN(100),
            limitTotal: new anchor.BN(1000),
            dailyLimit: new anchor.BN(500),
            weeklyLimit: new anchor.BN(2500),
            monthlyLimit: new anchor.BN(5000),
            cosignLimitPerTx: new anchor.BN(1000),
            cosignDailyLimit: new anchor.BN(5000),
            coSigner: PublicKey.default,
          })
          .accounts({
            owner: badOwner.publicKey,
            authority: authority.publicKey,
            wallet: badWalletPda,
            systemProgram: SystemProgram.programId,
          })
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("InvalidTrustLevel");
      }
    });
  });

  describe("execute_transfer", () => {
    before(async () => {
      // Create source ATA owned by wallet PDA and fund it
      // Must use getOrCreateAssociatedTokenAccount with allowOwnerOffCurve=true for PDAs
      const sourceAccount = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        (authority as any).payer,
        mint,
        walletPda,
        true // allowOwnerOffCurve — PDA is not on curve
      );
      sourceAta = sourceAccount.address;

      // Mint tokens to source
      await mintTo(
        provider.connection,
        (authority as any).payer,
        mint,
        sourceAta,
        authority.publicKey,
        100_000 * ONE_USDC
      );

      // Create destination ATA for merchant
      destinationAta = await createAssociatedTokenAccount(
        provider.connection,
        (authority as any).payer,
        mint,
        merchant.publicKey
      );
    });

    it("executes a valid transfer", async () => {
      const amount = 100 * ONE_USDC;

      await program.methods
        .executeTransfer(new anchor.BN(amount))
        .accounts({
          owner: owner.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
          tokenAllowlist: tokenAllowlistPda,
          source: sourceAta,
          destination: destinationAta,
          mint: mint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner])
        .rpc();

      // Verify destination received tokens
      const destAccount = await getAccount(
        provider.connection,
        destinationAta
      );
      expect(Number(destAccount.amount)).to.equal(amount);

      // Verify spend tracking
      const wallet = await program.account.agentWallet.fetch(walletPda);
      expect(wallet.spentTotal.toNumber()).to.equal(amount);
      expect(wallet.dailySpent.toNumber()).to.equal(amount);
    });

    it("rejects zero amount", async () => {
      try {
        await program.methods
          .executeTransfer(new anchor.BN(0))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: sourceAta,
            destination: destinationAta,
            mint: mint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("AmountMustBePositive");
      }
    });

    it("rejects transfer exceeding per-tx limit", async () => {
      const overLimit = 501 * ONE_USDC; // limit is 500

      try {
        await program.methods
          .executeTransfer(new anchor.BN(overLimit))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: sourceAta,
            destination: destinationAta,
            mint: mint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("PerTxLimitExceeded");
      }
    });
  });

  describe("freeze / unfreeze", () => {
    it("freezes wallet and blocks transfers", async () => {
      await program.methods
        .freezeWallet()
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();

      const wallet = await program.account.agentWallet.fetch(walletPda);
      expect(wallet.paused).to.equal(1);

      // Transfer should fail
      try {
        await program.methods
          .executeTransfer(new anchor.BN(ONE_USDC))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: sourceAta,
            destination: destinationAta,
            mint: mint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("WalletPaused");
      }
    });

    it("unfreezes wallet and allows transfers", async () => {
      await program.methods
        .unfreezeWallet()
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();

      const wallet = await program.account.agentWallet.fetch(walletPda);
      expect(wallet.paused).to.equal(0);

      // Transfer should succeed now
      await program.methods
        .executeTransfer(new anchor.BN(ONE_USDC))
        .accounts({
          owner: owner.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
          tokenAllowlist: tokenAllowlistPda,
          source: sourceAta,
          destination: destinationAta,
          mint: mint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner])
        .rpc();
    });
  });

  describe("merchant rules", () => {
    const deniedMerchant = Keypair.generate();

    it("adds a merchant deny rule", async () => {
      await program.methods
        .addMerchantRule(deniedMerchant.publicKey, 1, new anchor.BN(0)) // DENY
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
        })
        .rpc();

      const registry = await program.account.merchantRegistry.fetch(
        merchantRegistryPda
      );
      expect(registry.count).to.equal(1);
    });

    it("blocks transfers to denied merchant", async () => {
      const deniedAta = await createAssociatedTokenAccount(
        provider.connection,
        (authority as any).payer,
        mint,
        deniedMerchant.publicKey
      );

      try {
        await program.methods
          .executeTransfer(new anchor.BN(ONE_USDC))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: sourceAta,
            destination: deniedAta,
            mint: mint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("MerchantDenied");
      }
    });

    it("enables allowlist mode and blocks unlisted merchants", async () => {
      // First add the existing merchant as allowed
      await program.methods
        .addMerchantRule(merchant.publicKey, 0, new anchor.BN(0)) // ALLOW
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
        })
        .rpc();

      // Enable allowlist mode
      await program.methods
        .setAllowlistMode(true)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();

      // Transfer to allowed merchant should work
      await program.methods
        .executeTransfer(new anchor.BN(ONE_USDC))
        .accounts({
          owner: owner.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
          tokenAllowlist: tokenAllowlistPda,
          source: sourceAta,
          destination: destinationAta,
          mint: mint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner])
        .rpc();

      // Transfer to unknown merchant should fail
      const unknownMerchant = Keypair.generate();
      const unknownAta = await createAssociatedTokenAccount(
        provider.connection,
        (authority as any).payer,
        mint,
        unknownMerchant.publicKey
      );

      try {
        await program.methods
          .executeTransfer(new anchor.BN(ONE_USDC))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: sourceAta,
            destination: unknownAta,
            mint: mint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("MerchantNotAllowed");
      }

      // Disable allowlist for subsequent tests
      await program.methods
        .setAllowlistMode(false)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();
    });

    it("enforces per-merchant cap", async () => {
      // Remove existing merchant rule and re-add with cap
      await program.methods
        .removeMerchantRule(merchant.publicKey)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
        })
        .rpc();

      await program.methods
        .addMerchantRule(
          merchant.publicKey,
          0, // ALLOW
          new anchor.BN(50 * ONE_USDC) // 50 USDC cap
        )
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
        })
        .rpc();

      try {
        await program.methods
          .executeTransfer(new anchor.BN(51 * ONE_USDC))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: sourceAta,
            destination: destinationAta,
            mint: mint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("MerchantCapExceeded");
      }
    });
  });

  describe("token allowlist", () => {
    it("adds a token and enforces allowlist", async () => {
      // Add mint to allowlist
      await program.methods
        .addToken(mint)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          tokenList: tokenAllowlistPda,
        })
        .rpc();

      // Enable enforcement
      await program.methods
        .setTokenAllowlistEnforced(true)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();

      // Transfer with allowed token should work
      // (Remove merchant cap first)
      await program.methods
        .removeMerchantRule(merchant.publicKey)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
        })
        .rpc();

      await program.methods
        .executeTransfer(new anchor.BN(ONE_USDC))
        .accounts({
          owner: owner.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
          tokenAllowlist: tokenAllowlistPda,
          source: sourceAta,
          destination: destinationAta,
          mint: mint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner])
        .rpc();
    });

    it("blocks transfer of non-allowlisted token", async () => {
      // Create ATAs for secondMint — PDA owner needs allowOwnerOffCurve
      const source2Account = await getOrCreateAssociatedTokenAccount(
        provider.connection,
        (authority as any).payer,
        secondMint,
        walletPda,
        true // allowOwnerOffCurve
      );
      const source2 = source2Account.address;
      await mintTo(
        provider.connection,
        (authority as any).payer,
        secondMint,
        source2,
        authority.publicKey,
        10_000 * ONE_USDC
      );
      const dest2 = await createAssociatedTokenAccount(
        provider.connection,
        (authority as any).payer,
        secondMint,
        merchant.publicKey
      );

      try {
        await program.methods
          .executeTransfer(new anchor.BN(ONE_USDC))
          .accounts({
            owner: owner.publicKey,
            wallet: walletPda,
            merchantRegistry: merchantRegistryPda,
            tokenAllowlist: tokenAllowlistPda,
            source: source2,
            destination: dest2,
            mint: secondMint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err.error.errorCode.code).to.equal("TokenNotAllowed");
      }

      // Disable enforcement for subsequent tests
      await program.methods
        .setTokenAllowlistEnforced(false)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();
    });

    it("removes a token from allowlist", async () => {
      await program.methods
        .removeToken(mint)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
          tokenList: tokenAllowlistPda,
        })
        .rpc();

      const tokenList = await program.account.tokenAllowlist.fetch(
        tokenAllowlistPda
      );
      expect(tokenList.count).to.equal(0);
    });
  });

  describe("update_policy", () => {
    it("updates policy parameters", async () => {
      await program.methods
        .updatePolicy({
          trustLevel: 2, // HIGH
          limitPerTx: new anchor.BN(1000 * ONE_USDC),
          limitTotal: null,
          dailyLimit: new anchor.BN(10_000 * ONE_USDC),
          weeklyLimit: null,
          monthlyLimit: null,
          cosignLimitPerTx: null,
          cosignDailyLimit: null,
          coSigner: null,
        })
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();

      const wallet = await program.account.agentWallet.fetch(walletPda);
      expect(wallet.trustLevel).to.equal(2);
      expect(wallet.limitPerTx.toNumber()).to.equal(1000 * ONE_USDC);
      expect(wallet.dailyLimit.toNumber()).to.equal(10_000 * ONE_USDC);
      // Unchanged fields
      expect(wallet.weeklyLimit.toNumber()).to.equal(25_000 * ONE_USDC);
    });
  });

  describe("execute_cosigned_transfer", () => {
    it("executes transfer with elevated limits", async () => {
      const amount = 800 * ONE_USDC; // Within cosign limit, above old per-tx

      await program.methods
        .executeCosignedTransfer(new anchor.BN(amount))
        .accounts({
          owner: owner.publicKey,
          coSigner: coSigner.publicKey,
          wallet: walletPda,
          merchantRegistry: merchantRegistryPda,
          tokenAllowlist: tokenAllowlistPda,
          source: sourceAta,
          destination: destinationAta,
          mint: mint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner, coSigner])
        .rpc();

      const wallet = await program.account.agentWallet.fetch(walletPda);
      // Spend tracking should reflect all transfers
      expect(wallet.spentTotal.toNumber()).to.be.greaterThan(0);
    });
  });

  describe("update_authority", () => {
    it("transfers authority", async () => {
      const newAuthority = Keypair.generate();

      await program.methods
        .updateAuthority(newAuthority.publicKey)
        .accounts({
          authority: authority.publicKey,
          wallet: walletPda,
        })
        .rpc();

      const wallet = await program.account.agentWallet.fetch(walletPda);
      expect(wallet.authority.toBase58()).to.equal(
        newAuthority.publicKey.toBase58()
      );

      // Transfer back for remaining tests
      const sig = await provider.connection.requestAirdrop(
        newAuthority.publicKey,
        LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);

      await program.methods
        .updateAuthority(authority.publicKey)
        .accounts({
          authority: newAuthority.publicKey,
          wallet: walletPda,
        })
        .signers([newAuthority])
        .rpc();
    });
  });

  describe("close_wallet", () => {
    it("closes wallet and reclaims rent", async () => {
      // Create a separate wallet to close
      const closeOwner = Keypair.generate();
      const [closeWallet] = PublicKey.findProgramAddressSync(
        [Buffer.from("sardis_wallet"), closeOwner.publicKey.toBuffer()],
        program.programId
      );
      const [closeMerchant] = PublicKey.findProgramAddressSync(
        [Buffer.from("merchants"), closeWallet.toBuffer()],
        program.programId
      );
      const [closeTokens] = PublicKey.findProgramAddressSync(
        [Buffer.from("tokens"), closeWallet.toBuffer()],
        program.programId
      );

      await program.methods
        .initializeWallet({
          trustLevel: 0,
          limitPerTx: new anchor.BN(100),
          limitTotal: new anchor.BN(1000),
          dailyLimit: new anchor.BN(500),
          weeklyLimit: new anchor.BN(2500),
          monthlyLimit: new anchor.BN(5000),
          cosignLimitPerTx: new anchor.BN(1000),
          cosignDailyLimit: new anchor.BN(5000),
          coSigner: PublicKey.default,
        })
        .accounts({
          owner: closeOwner.publicKey,
          authority: authority.publicKey,
          wallet: closeWallet,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      await program.methods
        .initializeRegistries()
        .accounts({
          authority: authority.publicKey,
          wallet: closeWallet,
          merchantRegistry: closeMerchant,
          tokenAllowlist: closeTokens,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      const balanceBefore = await provider.connection.getBalance(
        authority.publicKey
      );

      await program.methods
        .closeWallet()
        .accounts({
          authority: authority.publicKey,
          owner: closeOwner.publicKey,
          wallet: closeWallet,
          merchantRegistry: closeMerchant,
          tokenList: closeTokens,
        })
        .rpc();

      const balanceAfter = await provider.connection.getBalance(
        authority.publicKey
      );
      expect(balanceAfter).to.be.greaterThan(balanceBefore);

      // Verify accounts are closed
      const info = await provider.connection.getAccountInfo(closeWallet);
      expect(info).to.be.null;
    });
  });
});
