import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const targets = [
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Stripe",
    website: "https://stripe.com",
    fitReason: "Directly shaping agentic commerce infrastructure and merchant checkout standards.",
    insertion: "Merchant and AI-platform checkout governance, approval logic, and spend-policy controls around agent-initiated purchases.",
    teamBuyer: "Head of Agentic Commerce, product partnerships, commerce platform, risk.",
    whyNow: "Co-developed ACP with OpenAI and launched Instant Checkout support plus broader agentic commerce tooling in late 2025.",
    fit: 10,
    confidence: 9,
    reachability: 4,
    personalization: 10,
    pilot: 5,
    signal: "Stripe newsroom on Instant Checkout, ACP, and agentic commerce suite."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Shopify",
    website: "https://www.shopify.com",
    fitReason: "Actively building the merchant operating layer for AI-native shopping channels.",
    insertion: "Governed checkout, merchant policy controls, and order-flow approvals inside AI channels and agentic storefronts.",
    teamBuyer: "VP Product, agentic commerce, checkout, merchant platform.",
    whyNow: "Launched Agentic Storefronts, UCP, and direct ChatGPT commerce integrations across late 2025 to early 2026.",
    fit: 10,
    confidence: 9,
    reachability: 5,
    personalization: 10,
    pilot: 6,
    signal: "Shopify news on Agentic Storefronts, UCP, and OpenAI commerce integration."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Checkout.com",
    website: "https://www.checkout.com",
    fitReason: "Explicitly positioning itself as the payment bridge between merchants and AI agents.",
    insertion: "Agent-initiated checkout guardrails, approvals, merchant controls, and orchestration for enterprise merchants.",
    teamBuyer: "Chief Product Officer, agentic commerce team, strategic partnerships.",
    whyNow: "Adopted ACP, is live with UCP-related flows, and publicly says agentic commerce is a core 2026 growth vector.",
    fit: 10,
    confidence: 9,
    reachability: 6,
    personalization: 10,
    pilot: 8,
    signal: "Checkout.com newsroom and annual letter emphasize agentic commerce and protocol support."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Coinbase",
    website: "https://www.coinbase.com",
    fitReason: "One of the clearest agent-payments infrastructure players, especially for x402 and agent wallets.",
    insertion: "Agent wallet guardrails, pay-per-use API spend controls, and autonomous payment authorization layers.",
    teamBuyer: "Developer platform, x402, agentic wallets, product partnerships.",
    whyNow: "Pushed x402, AP2 integrations, Browserbase payments, and launched Agentic Wallets in early 2026.",
    fit: 10,
    confidence: 9,
    reachability: 6,
    personalization: 9,
    pilot: 7,
    signal: "Coinbase developer platform announcements around x402, AP2, Browserbase, and Agentic Wallets."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Circle",
    website: "https://www.circle.com",
    fitReason: "Strong programmable-wallet and stablecoin rails layer that already references agent use cases.",
    insertion: "Policy-governed stablecoin wallets, treasury controls, and agent spend enforcement on top of Circle rails.",
    teamBuyer: "Programmable Wallets, developer platform, partnerships, product.",
    whyNow: "Circle tied wallets, x402, and autonomous commerce into its 2025 narrative and expanded modular wallets.",
    fit: 10,
    confidence: 9,
    reachability: 6,
    personalization: 9,
    pilot: 7,
    signal: "Circle wallet and year-in-review posts explicitly mention AI-agent use cases and x402."
  },
  {
    tier: "Tier 1",
    track: "A1 Agent platforms / agent builders",
    company: "OpenAI",
    website: "https://openai.com",
    fitReason: "Has already turned ChatGPT into a commerce surface and needs trusted payment-control patterns around agent action.",
    insertion: "Merchant onboarding, approval controls, and policy-aware checkout for higher-stakes or multi-step purchases inside ChatGPT.",
    teamBuyer: "Commerce, product, partnerships, applications.",
    whyNow: "Instant Checkout and ACP are live, with plans to expand merchants, carts, and geographies.",
    fit: 9,
    confidence: 9,
    reachability: 2,
    personalization: 10,
    pilot: 4,
    signal: "OpenAI launched Instant Checkout in ChatGPT and the Agentic Commerce Protocol."
  },
  {
    tier: "Tier 1",
    track: "A1 Agent platforms / agent builders",
    company: "Anthropic",
    website: "https://www.anthropic.com",
    fitReason: "Enterprise agent workflows increasingly need safe action-taking, not just reasoning.",
    insertion: "Governed spend actions for enterprise Claude agents that touch research, procurement, software, or vendor workflows.",
    teamBuyer: "Claude for Enterprise, product, solutions engineering, partnerships.",
    whyNow: "Anthropic keeps expanding Claude’s action surface and enterprise autonomy, while partners like Intuit are pushing finance agents.",
    fit: 9,
    confidence: 8,
    reachability: 4,
    personalization: 9,
    pilot: 6,
    signal: "Anthropic posts on agentic research, sandboxing, and enterprise production use."
  },
  {
    tier: "Tier 1",
    track: "A1 Agent platforms / agent builders",
    company: "Replit",
    website: "https://replit.com",
    fitReason: "Developer agents are already wiring payment flows and Stripe integrations from inside the product.",
    insertion: "Safe payment actions for app-building agents, especially when agents add subscriptions or paid APIs for end-users.",
    teamBuyer: "Agent product, platform, monetization, partnerships.",
    whyNow: "Replit’s Agent and Stripe payment integration make real financial actions increasingly native to the build flow.",
    fit: 9,
    confidence: 8,
    reachability: 7,
    personalization: 8,
    pilot: 8,
    signal: "Replit docs now show Agent-led Stripe payment integration and sandbox-to-live workflows."
  },
  {
    tier: "Tier 1",
    track: "A1 Agent platforms / agent builders",
    company: "Vercel",
    website: "https://vercel.com",
    fitReason: "Becoming a core distribution layer for production agent apps with unified billing and marketplace workflows.",
    insertion: "Payment controls around agents provisioning services, metered AI billing, and marketplace-driven purchases.",
    teamBuyer: "AI Cloud, marketplace, billing, platform partnerships.",
    whyNow: "Vercel launched AI Cloud, AI agent marketplace, Stripe billing for AI Gateway, and agent-friendly integration discovery.",
    fit: 9,
    confidence: 8,
    reachability: 7,
    personalization: 8,
    pilot: 8,
    signal: "Vercel blog and docs on AI Cloud, marketplace, and Stripe billing integration."
  },
  {
    tier: "Tier 1",
    track: "A1 Agent platforms / agent builders",
    company: "LangChain",
    website: "https://www.langchain.com",
    fitReason: "Core agent engineering platform with a strong enterprise base that already cares about controls and HITL.",
    insertion: "Payments as a governed tool in agent graphs, with approvals and policy evaluation for production agents.",
    teamBuyer: "Platform, LangSmith deployment, enterprise product, partnerships.",
    whyNow: "Raised new funding, expanded no-code agent building, and publicly highlights customers running complex agent workflows.",
    fit: 9,
    confidence: 9,
    reachability: 7,
    personalization: 9,
    pilot: 8,
    signal: "LangChain funding post and product pages emphasize reliable agent engineering, HITL, and enterprise deployment."
  },
  {
    tier: "Tier 1",
    track: "A1 Agent platforms / agent builders",
    company: "Browserbase",
    website: "https://www.browserbase.com",
    fitReason: "Already monetizing autonomous browser sessions through x402, which maps tightly to Sardis’s core thesis.",
    insertion: "Policy-bound payment execution for agents that browse, buy, and transact in real browser sessions.",
    teamBuyer: "Product, developer platform, agentic payments partnerships.",
    whyNow: "Launched x402-paid browser sessions with Coinbase, making autonomous spend a live product surface.",
    fit: 10,
    confidence: 9,
    reachability: 8,
    personalization: 8,
    pilot: 9,
    signal: "Browserbase and Coinbase both announced pay-per-use browser sessions over x402."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Lithic",
    website: "https://www.lithic.com",
    fitReason: "Card issuance is one of Sardis’s clearest adjacent surfaces, and Lithic is openly talking about agentic payments.",
    insertion: "Virtual-card controls, authorization rules, and approval workflows for AI-led purchasing or bill pay.",
    teamBuyer: "GM payments, product, issuer solutions, partnerships.",
    whyNow: "Lithic published directly on agentic payments and bill-pay use cases that require spend policies and authorization rules.",
    fit: 9,
    confidence: 9,
    reachability: 7,
    personalization: 8,
    pilot: 9,
    signal: "Lithic posts on agentic payments and AI-driven bill-pay workflows."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Airwallex",
    website: "https://www.airwallex.com",
    fitReason: "Finance and spend agents are already part of the Airwallex roadmap, which makes policy control directly relevant.",
    insertion: "Approval thresholds, anomaly detection, and governed spend inside AP, expense, and treasury agents.",
    teamBuyer: "Spend, finance automation, AI product, platform partnerships.",
    whyNow: "Airwallex launched finance AI agents and is publicly framing AI-agent finance workflows as a core direction.",
    fit: 9,
    confidence: 8,
    reachability: 7,
    personalization: 8,
    pilot: 8,
    signal: "Airwallex blog on finance AI agents and AI-agent finance positioning."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Spreedly",
    website: "https://www.spreedly.com",
    fitReason: "Open-payments orchestration plus live agentic commerce is almost perfectly aligned with Sardis’s control-plane value.",
    insertion: "Merchant-facing orchestration where agent-initiated payments need vaulting, routing, and spend-rule enforcement.",
    teamBuyer: "Open payments platform, product, partnerships, merchant solutions.",
    whyNow: "Spreedly made agentic commerce a live channel in March 2026 and is already testing real merchant flows.",
    fit: 10,
    confidence: 9,
    reachability: 7,
    personalization: 9,
    pilot: 9,
    signal: "Spreedly announced agentic commerce is live and highlighted guardrails like limits and token enforcement."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Primer",
    website: "https://www.primer.io",
    fitReason: "Payment orchestration with no-code workflows creates a natural insertion point for Sardis policy logic.",
    insertion: "Route agent-originated or merchant-initiated payment flows through approval, fallback, and risk decision nodes.",
    teamBuyer: "Payments platform, workflows, orchestration, product.",
    whyNow: "Primer is leaning into modular orchestration for travel and high-complexity verticals where policy control matters.",
    fit: 9,
    confidence: 8,
    reachability: 8,
    personalization: 8,
    pilot: 9,
    signal: "Primer docs and blogs on workflows, travel orchestration, and unified payment infrastructure."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Payrails",
    website: "https://www.payrails.com",
    fitReason: "Modern payment operating system for enterprises, with strong workflow and analytics overlap.",
    insertion: "Agent payment approvals, exception handling, reconciliation-aware controls, and enterprise payment operations.",
    teamBuyer: "Product, enterprise solutions, payment ops platform.",
    whyNow: "Raised capital, expanded modular payment OS capabilities, and is actively pushing AI and anomaly-detection narratives.",
    fit: 9,
    confidence: 8,
    reachability: 8,
    personalization: 7,
    pilot: 9,
    signal: "Payrails funding, Mastercard partnership, and ML/anomaly detection announcements."
  },
  {
    tier: "Tier 1",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Ramp",
    website: "https://ramp.com",
    fitReason: "One of the clearest finance-agent companies, already automating policy reviews and spend operations.",
    insertion: "Controlled payment execution for controller agents, AP workflows, and autonomous out-of-policy review flows.",
    teamBuyer: "Finance automation, AI product, spend controls, platform.",
    whyNow: "Ramp agents are live and the company explicitly frames them as autonomous reviewers for finance operations.",
    fit: 9,
    confidence: 9,
    reachability: 7,
    personalization: 9,
    pilot: 8,
    signal: "Ramp’s 2025 agents announcement and AP/finance agent content."
  },
  {
    tier: "Tier 1",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Navan",
    website: "https://navan.com",
    fitReason: "Travel and expense is a natural wedge for agentic spend controls because payments, policy, and exceptions collide constantly.",
    insertion: "Travel policy enforcement, card controls, expense-chat approvals, and out-of-pocket spend automation.",
    teamBuyer: "Travel/expense AI, card product, finance automation, product strategy.",
    whyNow: "Navan keeps shipping travel and expense agents, including Expense Chat in March 2026.",
    fit: 9,
    confidence: 9,
    reachability: 7,
    personalization: 9,
    pilot: 8,
    signal: "Navan press and blog on specialist travel and expense agents."
  },
  {
    tier: "Tier 1",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Zip",
    website: "https://ziphq.com",
    fitReason: "Procurement orchestration is one of the most obvious enterprise workflows where agents need bounded payment authority.",
    insertion: "Vendor intake, renewal review, risk screening, and AI-assisted approvals before a payment or purchase action.",
    teamBuyer: "AI procurement, orchestration platform, product leadership.",
    whyNow: "Zip is pushing agentic procurement orchestration and publishing AI adoption data from procurement leaders.",
    fit: 8,
    confidence: 9,
    reachability: 8,
    personalization: 8,
    pilot: 9,
    signal: "Zip AI pages, procurement survey data, and 2025 platform positioning."
  },
  {
    tier: "Tier 1",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Intuit",
    website: "https://www.intuit.com",
    fitReason: "Few companies are building finance-native agents as aggressively as Intuit across AR/AP, accounting, tax, and payments.",
    insertion: "Governed spend and payment actions inside QuickBooks, Enterprise Suite, and finance agent workflows.",
    teamBuyer: "GenOS, payments, finance automation, enterprise suite product.",
    whyNow: "Intuit is shipping agentic AI across consumers and businesses and partnering with Anthropic for finance agents.",
    fit: 9,
    confidence: 9,
    reachability: 5,
    personalization: 9,
    pilot: 6,
    signal: "Intuit investor releases on GenOS, AR/AP agents, and Anthropic partnership."
  },
  {
    tier: "Tier 1",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Workday",
    website: "https://www.workday.com",
    fitReason: "Manages people, money, and now agents, making it a strong fit for governed payment actions inside enterprise systems.",
    insertion: "Workday agent workflows that need payment approvals, policy checks, and financial control boundaries.",
    teamBuyer: "Agent System of Record, finance product, marketplace, partnerships.",
    whyNow: "Workday has made agent governance a category with ASOR, agent marketplace, and finance-related role agents.",
    fit: 9,
    confidence: 9,
    reachability: 6,
    personalization: 9,
    pilot: 7,
    signal: "Workday ASOR and partner-network announcements, plus role-based finance and policy agents."
  },
  {
    tier: "Tier 1",
    track: "A2 Internal enterprise AI & automation teams",
    company: "ServiceNow",
    website: "https://www.servicenow.com",
    fitReason: "Strong governance-and-orchestration posture makes it a natural home for enterprise payment action controls.",
    insertion: "AI agents that span procurement, CRM, service, and operations but need explicit payment or purchase guardrails.",
    teamBuyer: "AI platform, AI Control Tower, agent fabric, workflow product.",
    whyNow: "ServiceNow is explicitly selling AI governance, AI Control Tower, and cross-workflow agent orchestration.",
    fit: 8,
    confidence: 9,
    reachability: 5,
    personalization: 9,
    pilot: 6,
    signal: "ServiceNow AI Control Tower, AI Experience, and agent fabric announcements."
  },
  {
    tier: "Tier 1",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Klarna",
    website: "https://www.klarna.com",
    fitReason: "Consumer shopping, refunds, and payment support agents make Klarna a direct testbed for governed autonomous actions.",
    insertion: "Shopping and support agents that trigger refunds, purchase recommendations, and payment-resolution actions.",
    teamBuyer: "AI assistant, shopping product, risk, payments product.",
    whyNow: "Klarna remains one of the most public agentic-commerce brands and has public case studies around payment-facing AI assistants.",
    fit: 8,
    confidence: 8,
    reachability: 6,
    personalization: 8,
    pilot: 7,
    signal: "Klarna AI assistant case studies and public shopping-assistant narrative."
  },
  {
    tier: "Tier 1",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Rippling",
    website: "https://www.rippling.com",
    fitReason: "Finance, payroll, identity, and spend are already unified, so adding payment-governed agents is plausible.",
    insertion: "Expense, procurement, payroll-adjacent, and device or vendor actions that need financial controls.",
    teamBuyer: "Platform, spend, product, automation leadership.",
    whyNow: "Rippling shows up repeatedly in the modern agent stack and has adjacent spend and finance workflows where control matters.",
    fit: 8,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 7,
    signal: "LangChain customer references and Rippling’s broader platform expansion around spend and automation."
  },
  {
    tier: "Tier 1",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Treasury Prime",
    website: "https://www.treasuryprime.com",
    fitReason: "Embedded finance infrastructure with an AI-native narrative and compliance-sensitive partner workflows.",
    insertion: "Bank-fintech onboarding, embedded payments, and governed financial actions inside marketplace-style partner flows.",
    teamBuyer: "BankOS, marketplace, product, partnerships.",
    whyNow: "Treasury Prime launched an AI Marketplace and is stressing auditable, direct-control infrastructure after BaaS trust shocks.",
    fit: 8,
    confidence: 8,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Treasury Prime AI Marketplace launch and BankOS compliance-first positioning."
  },

  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Microsoft",
    website: "https://www.microsoft.com",
    fitReason: "Copilot is becoming a commerce and agent surface that will eventually need safer action and payment boundaries.",
    insertion: "Copilot checkout and agent task execution where purchases or paid service calls require policy controls.",
    teamBuyer: "Copilot product, commerce, business apps, partnerships.",
    whyNow: "Stripe called out Microsoft Copilot as an early agentic commerce partner and Shopify is rolling out Copilot checkout.",
    fit: 8,
    confidence: 9,
    reachability: 3,
    personalization: 10,
    pilot: 4,
    signal: "Stripe and Shopify both reference Microsoft Copilot in agentic commerce rollouts."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Google Cloud",
    website: "https://cloud.google.com",
    fitReason: "Google is defining agent payment and commerce protocols that will need trusted control layers.",
    insertion: "AP2 and commerce protocol flows where agents need approval rules, merchant controls, and payment governance.",
    teamBuyer: "Google Cloud agents, commerce, protocol partnerships.",
    whyNow: "Google’s work with Coinbase on AP2 and Shopify on UCP shows clear momentum toward agent payment standards.",
    fit: 8,
    confidence: 8,
    reachability: 4,
    personalization: 9,
    pilot: 4,
    signal: "Coinbase AP2 launch post and Shopify UCP announcement."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "LlamaIndex",
    website: "https://www.llamaindex.ai",
    fitReason: "Enterprise agent builders need safer action patterns once RAG evolves into execution.",
    insertion: "Tool-driven enterprise agents that move from retrieval and reasoning into paid actions or purchases.",
    teamBuyer: "Platform, enterprise product, solutions engineering.",
    whyNow: "LlamaIndex keeps positioning around enterprise agents and complex workflows, which increases the value of action controls.",
    fit: 8,
    confidence: 7,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "LlamaIndex enterprise-agent positioning and workflow narrative."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Cognition",
    website: "https://cognition.ai",
    fitReason: "Autonomous coding agents increasingly touch subscriptions, infrastructure, and paid API usage.",
    insertion: "Safe financial actions when developer agents procure services or trigger paid tooling on behalf of teams.",
    teamBuyer: "Platform, product, developer infrastructure.",
    whyNow: "The market is shifting from code assistance to more autonomous software execution, where payment boundaries matter more.",
    fit: 8,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 7,
    signal: "Public product direction toward increasingly autonomous software agents."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Glean",
    website: "https://www.glean.com",
    fitReason: "Enterprise knowledge agents are moving toward action-taking inside sensitive workflows.",
    insertion: "Research and internal assistants that initiate vendor, purchasing, or software procurement tasks.",
    teamBuyer: "Product, platform, enterprise AI solutions.",
    whyNow: "Glean’s enterprise AI posture makes action governance more relevant as assistants move from search into workflow execution.",
    fit: 7,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 7,
    signal: "Strong enterprise agent trajectory and workflow-expansion narrative."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Moveworks",
    website: "https://www.moveworks.com",
    fitReason: "Enterprise copilots that span IT, HR, and business operations could benefit from governed payment actions.",
    insertion: "Employee-facing agents that resolve tasks, trigger approvals, and potentially kick off paid services or procurement flows.",
    teamBuyer: "Product, AI platform, enterprise solutions.",
    whyNow: "As enterprise assistants expand scope, spend and approval controls become more important than simple automation.",
    fit: 7,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 6,
    signal: "Broader move from support automation into cross-enterprise agent execution."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "UiPath",
    website: "https://www.uipath.com",
    fitReason: "Agentic automation is converging with process automation, where payment steps need explicit control.",
    insertion: "RPA plus AI agent workflows that enter procurement, invoicing, or payment exception processes.",
    teamBuyer: "Agentic automation, product, enterprise transformation.",
    whyNow: "UiPath is pushing agentic automation for enterprise workflows that increasingly touch financial operations.",
    fit: 7,
    confidence: 8,
    reachability: 6,
    personalization: 8,
    pilot: 7,
    signal: "UiPath’s agentic automation category push."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Automation Anywhere",
    website: "https://www.automationanywhere.com",
    fitReason: "Financial-process automation is a natural place for Sardis if agents start making bounded payment decisions.",
    insertion: "Accounts payable, procurement, and back-office automation where payment actions need policy review.",
    teamBuyer: "Product, AI agents, finance automation.",
    whyNow: "The company is broadening from automation into agentic process execution across enterprise operations.",
    fit: 7,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 6,
    signal: "Public move toward agentic process automation."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "n8n",
    website: "https://n8n.io",
    fitReason: "Workflow builders are a natural wedge because Sardis can become the safe payment action inside low-code automation.",
    insertion: "Low-code agent workflows that need a controlled purchase, card, or treasury action step.",
    teamBuyer: "Platform, community/product, partnerships.",
    whyNow: "n8n remains a favored builder for agentic workflows, making payment-as-tool packaging increasingly relevant.",
    fit: 7,
    confidence: 7,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Strong agentic automation adoption in the n8n ecosystem."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Zapier",
    website: "https://zapier.com",
    fitReason: "Zapier’s AI actions and agentic workflows create a broad distribution surface for governed payment steps.",
    insertion: "User-built automations where agents trigger purchases, invoices, subscriptions, or vendor tasks.",
    teamBuyer: "AI product, platform partnerships, ecosystem.",
    whyNow: "More users are moving from automation recipes to AI-led actions, which raises the stakes of payment controls.",
    fit: 7,
    confidence: 7,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Zapier’s continued AI-actions expansion and broad SMB workflow footprint."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Dust",
    website: "https://dust.tt",
    fitReason: "Enterprise internal assistants increasingly become workflow doers, not just answer engines.",
    insertion: "Internal research and ops agents that may need controlled spending or vendor interactions.",
    teamBuyer: "Product, enterprise solutions, platform.",
    whyNow: "Dust’s enterprise assistant posture makes Sardis relevant as customers push assistants into operational workflows.",
    fit: 8,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Enterprise assistant positioning and action-oriented assistant use cases."
  },
  {
    tier: "Tier 2",
    track: "A1 Agent platforms / agent builders",
    company: "Writer",
    website: "https://writer.com",
    fitReason: "Writer is moving into enterprise agents with strong governance expectations already in the room.",
    insertion: "Enterprise agent tasks that need explicit budget, procurement, or payment boundaries.",
    teamBuyer: "Product, enterprise AI, platform partnerships.",
    whyNow: "Writer is increasingly positioned as an enterprise AI platform, not just a content tool.",
    fit: 7,
    confidence: 7,
    reachability: 6,
    personalization: 8,
    pilot: 6,
    signal: "Enterprise AI platform narrative and workflow expansion."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Salesforce",
    website: "https://www.salesforce.com",
    fitReason: "Agentforce is spreading across commerce and revenue workflows where approved transactions may become native.",
    insertion: "Agent-led commerce, renewals, quoting, and customer workflows that require payment or refund controls.",
    teamBuyer: "Agentforce commerce, AI platform, digital commerce product.",
    whyNow: "Salesforce is pushing Agentforce Commerce and highlighting AI-driven order growth and new AI channels.",
    fit: 8,
    confidence: 9,
    reachability: 4,
    personalization: 10,
    pilot: 5,
    signal: "Salesforce commerce and Agentforce announcements across 2025."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "SAP",
    website: "https://www.sap.com",
    fitReason: "SAP already has agents across finance and procurement, which is a direct insertion point for Sardis.",
    insertion: "Procurement, disputes, collections, and finance agents that need governed payment execution.",
    teamBuyer: "Joule agents, finance product, procurement product.",
    whyNow: "SAP’s Joule agents now span finance and procurement, with explicit grounding in multi-step business processes.",
    fit: 8,
    confidence: 8,
    reachability: 4,
    personalization: 8,
    pilot: 5,
    signal: "SAP news center posts on Joule agents in finance, procurement, and cash collection."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Oracle",
    website: "https://www.oracle.com",
    fitReason: "ERP-driven enterprise agents create natural pressure for payment and procurement control layers.",
    insertion: "Finance, ERP, procurement, and supply-chain agent workflows with bounded spend authority.",
    teamBuyer: "AI apps, ERP/finance product, cloud apps leadership.",
    whyNow: "Oracle is leaning into enterprise AI inside systems that already govern money and approvals.",
    fit: 7,
    confidence: 7,
    reachability: 3,
    personalization: 8,
    pilot: 4,
    signal: "Oracle’s enterprise-AI posture in finance and ERP."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Cisco",
    website: "https://www.cisco.com",
    fitReason: "Large enterprise workflows, AI collaboration, and procurement-heavy operations make Cisco a plausible control-layer buyer.",
    insertion: "Internal AI agents that handle vendor, IT, and operations tasks needing approval before any spend or service action.",
    teamBuyer: "Enterprise AI, collaboration AI, internal platform leaders.",
    whyNow: "Cisco is publicly pushing agentic AI collaboration and shows up in partner ecosystems like Workday and ServiceNow.",
    fit: 7,
    confidence: 7,
    reachability: 4,
    personalization: 8,
    pilot: 4,
    signal: "Cisco newsroom and partner references around agentic AI collaboration."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "HubSpot",
    website: "https://www.hubspot.com",
    fitReason: "SMB-facing growth platform with AI assistants could eventually operationalize purchases, payments, or service actions.",
    insertion: "Revenue and support agents that need controlled payment requests or customer-facing billing actions.",
    teamBuyer: "AI product, revenue ops platform, product leadership.",
    whyNow: "HubSpot continues broadening AI across GTM workflows where downstream transactional actions are likely.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 6,
    signal: "HubSpot’s continuing AI expansion across revenue workflows."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Atlassian",
    website: "https://www.atlassian.com",
    fitReason: "Large internal workflow footprint means agents can eventually cross from work orchestration into paid actions.",
    insertion: "Ops and service workflows where procurement or vendor steps need controlled financial execution.",
    teamBuyer: "AI platform, automation, Jira/ops product leaders.",
    whyNow: "Atlassian continues pushing AI across work management, making execution governance more relevant over time.",
    fit: 7,
    confidence: 6,
    reachability: 6,
    personalization: 7,
    pilot: 5,
    signal: "Ongoing AI expansion across Atlassian’s work management surface."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Block",
    website: "https://block.xyz",
    fitReason: "Square, Cash App, and merchant/payments surfaces create many places where agentic commerce controls could matter.",
    insertion: "Merchant tools, internal payment ops, and SMB finance workflows with approval thresholds or spend bounds.",
    teamBuyer: "Commerce, AI, risk, merchant product.",
    whyNow: "Block remains a plausible design partner if merchant-facing AI and automation deepen across its ecosystem.",
    fit: 7,
    confidence: 6,
    reachability: 5,
    personalization: 7,
    pilot: 6,
    signal: "Strong adjacency across merchant, payments, and developer surfaces."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Deel",
    website: "https://www.deel.com",
    fitReason: "Cross-border payroll and contractor workflows are rich with governed payment and approval needs.",
    insertion: "Contractor payments, HR ops, onboarding, and vendor workflows that may gain autonomous task execution.",
    teamBuyer: "Global payroll, platform, AI/automation, product.",
    whyNow: "Global workforce ops are getting more automated, and payment compliance remains central.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Strong global workforce/payment adjacency and automation pressure."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Mercury",
    website: "https://mercury.com",
    fitReason: "Startup banking plus finance workflows creates a plausible home for agentic spend controls and treasury actions.",
    insertion: "Finance ops, approvals, vendor payments, and treasury-agent workflows.",
    teamBuyer: "Product, treasury, spend management, AI product.",
    whyNow: "Mercury’s customer base will increasingly expect finance automation with clear spend boundaries.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 6,
    pilot: 7,
    signal: "Startup finance platform adjacency to controlled treasury and spend actions."
  },
  {
    tier: "Tier 2",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Toast",
    website: "https://pos.toasttab.com",
    fitReason: "Restaurant payments, procurement, and operations make agentic commerce controls commercially relevant.",
    insertion: "Merchant AI, hospitality ops, supplier ordering, and payment exception workflows.",
    teamBuyer: "Payments, platform, restaurant ops product.",
    whyNow: "Hospitality and order-management workflows are becoming more automated while payment risk remains acute.",
    fit: 7,
    confidence: 6,
    reachability: 6,
    personalization: 7,
    pilot: 6,
    signal: "Strong vertical fit around hospitality payments and operations."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Modern Treasury",
    website: "https://www.moderntreasury.com",
    fitReason: "Treasury orchestration and payment ops already sit close to the control plane Sardis is building.",
    insertion: "Approval-aware treasury and money movement workflows, especially where AI begins to recommend or execute transfers.",
    teamBuyer: "Treasury product, platform, enterprise solutions.",
    whyNow: "Treasury teams are moving toward automation and real-time controls, which makes governance around AI actions timely.",
    fit: 8,
    confidence: 7,
    reachability: 7,
    personalization: 7,
    pilot: 8,
    signal: "Modern Treasury’s positioning around programmable money movement and treasury operations."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Unit",
    website: "https://www.unit.co",
    fitReason: "Embedded finance infrastructure benefits from a neutral action-control layer for accounts, cards, and payouts.",
    insertion: "BaaS and embedded-finance customers that want agent-safe approvals and spend controls.",
    teamBuyer: "Product, platform, embedded finance partnerships.",
    whyNow: "Embedded finance buyers increasingly care about auditable control, especially after BaaS trust shocks.",
    fit: 8,
    confidence: 6,
    reachability: 8,
    personalization: 6,
    pilot: 8,
    signal: "Clear adjacency to cards, accounts, and embedded money movement."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Highnote",
    website: "https://highnote.com",
    fitReason: "Unified issuing and acquiring could pair well with Sardis’s governed-agent payment layer.",
    insertion: "Embedded card and merchant-acquiring flows where AI-led actions need bounded approval and risk checks.",
    teamBuyer: "Product, acquiring, issuing, partnerships.",
    whyNow: "Highnote expanded into merchant acquiring and keeps pushing a unified embedded-payments platform story.",
    fit: 8,
    confidence: 7,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Highnote Series B and merchant acquiring expansion announcement."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Marqeta",
    website: "https://www.marqeta.com",
    fitReason: "Issuer processing and card controls are close to Sardis’s cards and approval surface.",
    insertion: "Card authorization logic, merchant restrictions, and dynamic controls for agent-led spend.",
    teamBuyer: "Issuing platform, product, strategic partnerships.",
    whyNow: "Card infrastructure players will need a better story for agent-controlled spend than raw authorization rails alone.",
    fit: 8,
    confidence: 6,
    reachability: 6,
    personalization: 6,
    pilot: 6,
    signal: "Strong adjacency to dynamic card controls and issuing."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Adyen",
    website: "https://www.adyen.com",
    fitReason: "Collaborating on agent payment protocols makes Adyen a logical strategic target for control-layer discussions.",
    insertion: "Merchant payment controls for agent-initiated transactions across global enterprise commerce.",
    teamBuyer: "Innovation, product, commerce, partnerships.",
    whyNow: "Adyen publicly joined Google’s agent payments work, signaling active interest rather than distant observation.",
    fit: 8,
    confidence: 8,
    reachability: 5,
    personalization: 9,
    pilot: 6,
    signal: "Adyen post on collaborating with Google on agent payments protocol."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "PayPal",
    website: "https://www.paypal.com",
    fitReason: "Huge consumer and merchant footprint makes it strategically relevant once agentic checkout grows.",
    insertion: "Wallet, merchant, and checkout flows where trusted delegated payment and policy controls matter.",
    teamBuyer: "Consumer commerce, checkout, AI product, risk.",
    whyNow: "PayPal is strategically relevant for agentic commerce even if pilot likelihood is lower than mid-market platforms.",
    fit: 8,
    confidence: 7,
    reachability: 4,
    personalization: 8,
    pilot: 4,
    signal: "Large consumer checkout footprint and AI-commerce adjacency."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "BVNK",
    website: "https://www.bvnk.com",
    fitReason: "Stablecoin payments plus AI assistant launch makes BVNK unusually aligned with Sardis’s autonomous-finance thesis.",
    insertion: "Treasury, wallet, compliance, and customer-facing assistant flows that need policy-safe transaction execution.",
    teamBuyer: "Product, stablecoin infrastructure, AI initiatives, partnerships.",
    whyNow: "BVNK publicly framed AI plus stablecoin infrastructure as a core 2025 direction and shipped an AI assistant.",
    fit: 8,
    confidence: 8,
    reachability: 8,
    personalization: 8,
    pilot: 8,
    signal: "BVNK AI assistant launch and stablecoin-plus-AI positioning."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Mollie",
    website: "https://www.mollie.com",
    fitReason: "Mollie is already exposing AI-ready operational surfaces through MCP, which overlaps with Sardis distribution.",
    insertion: "Merchant-side automation, insights, and workflow actions with guarded payment steps.",
    teamBuyer: "Developer platform, AI integrations, merchant tooling.",
    whyNow: "Mollie launched an AI-ready MCP server specifically to simplify merchant workflows using AI.",
    fit: 7,
    confidence: 8,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Mollie MCP server launch announcement."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "TrueLayer",
    website: "https://www.truelayer.com",
    fitReason: "Open-banking payment initiation is a strong future rail for agent-approved bank payments.",
    insertion: "Pay-by-bank and account-to-account agent payments with clear consent and bounded authority.",
    teamBuyer: "Product, open banking, partnerships.",
    whyNow: "If agentic commerce expands beyond cards, open-banking control layers become more relevant.",
    fit: 7,
    confidence: 7,
    reachability: 7,
    personalization: 6,
    pilot: 7,
    signal: "Strong strategic adjacency via pay-by-bank and regulated payment initiation."
  },
  {
    tier: "Tier 2",
    track: "A3 Fintech / commerce / payment design partners",
    company: "GoCardless",
    website: "https://gocardless.com",
    fitReason: "Recurring payments and bank debit workflows could benefit from more explicit agent controls over collection actions.",
    insertion: "Subscription, invoicing, and recurring-payment agents with approval and threshold logic.",
    teamBuyer: "Product, payment strategy, partnerships.",
    whyNow: "Useful as a broader recurring-payments and bank-debit angle, though less immediate than checkout-heavy players.",
    fit: 7,
    confidence: 6,
    reachability: 6,
    personalization: 6,
    pilot: 6,
    signal: "Recurring-payments adjacency with potential agent collection workflows."
  },
  {
    tier: "Tier 2",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Brex",
    website: "https://www.brex.com",
    fitReason: "Corporate spend, cards, and finance automation make Brex a natural target for policy-governed AI actions.",
    insertion: "Spend agent workflows, card policy controls, and AP or procurement automation.",
    teamBuyer: "Spend management, product, AI, finance automation.",
    whyNow: "Brex is structurally close to Ramp and Navan in the workflows Sardis best addresses.",
    fit: 8,
    confidence: 8,
    reachability: 7,
    personalization: 8,
    pilot: 7,
    signal: "Strong structural fit in corporate spend and finance automation."
  },
  {
    tier: "Tier 2",
    track: "A4 Procurement / travel / marketplace operators",
    company: "TravelPerk",
    website: "https://www.travelperk.com",
    fitReason: "Travel booking plus expense automation is one of the highest-friction payment workflows for agents.",
    insertion: "Policy-safe travel booking, reimbursement, and expense automation across enterprise travel.",
    teamBuyer: "Travel platform, expense product, AI/automation leadership.",
    whyNow: "TravelPerk, now branded Perk in some surfaces, is leaning into AI-native travel and expense automation.",
    fit: 8,
    confidence: 7,
    reachability: 7,
    personalization: 8,
    pilot: 8,
    signal: "Referenced in Navan’s 2026 AI-travel comparisons as an AI-native travel platform."
  },
  {
    tier: "Tier 2",
    track: "A4 Procurement / travel / marketplace operators",
    company: "GetYourGuide",
    website: "https://www.getyourguide.com",
    fitReason: "Travel-experience commerce plus orchestration-heavy payments make this a good mid-market design-partner candidate.",
    insertion: "Agent-driven booking and payment routing for travel experiences where exceptions and refunds are common.",
    teamBuyer: "Payments, product, growth platform.",
    whyNow: "Primer highlights travel as a core orchestration vertical and cites GetYourGuide as a representative operator.",
    fit: 7,
    confidence: 7,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Referenced in payment-orchestration-for-travel material."
  },

  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "eBay",
    website: "https://www.ebayinc.com",
    fitReason: "Marketplace shopping agents and seller AI tools make eBay a relevant agentic commerce target.",
    insertion: "Buyer-side agent shopping, seller-side automation, and policy-controlled marketplace checkout paths.",
    teamBuyer: "Marketplace product, AI commerce, payments, trust.",
    whyNow: "eBay has public OpenAI collaboration around shopping agents and keeps rolling out AI seller tooling.",
    fit: 7,
    confidence: 8,
    reachability: 5,
    personalization: 8,
    pilot: 6,
    signal: "eBay OpenAI/Operator references and AI Activate program."
  },
  {
    tier: "Tier 3",
    track: "A1 Agent platforms / agent builders",
    company: "Sierra",
    website: "https://www.sierra.ai",
    fitReason: "Customer-facing agents will eventually need safer ways to trigger refunds, purchases, or service payments.",
    insertion: "Service agents that move from answering to acting inside account and payment workflows.",
    teamBuyer: "Product, solutions, enterprise platform.",
    whyNow: "As Sierra expands customer-action surfaces, policy-governed financial actions become more relevant.",
    fit: 6,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 6,
    signal: "Customer-agent category expansion toward more action-oriented workflows."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Upwork",
    website: "https://www.upwork.com",
    fitReason: "AI work agents plus a work marketplace create opportunities for governed payment or purchase flows.",
    insertion: "Hiring, talent procurement, and managed-service workflows where AI agents could commit spend or route payments.",
    teamBuyer: "AI product, marketplace product, payments, enterprise product.",
    whyNow: "Upwork has evolved Uma into an AI work agent and is leaning into AI-powered marketplace outcomes.",
    fit: 6,
    confidence: 7,
    reachability: 6,
    personalization: 8,
    pilot: 6,
    signal: "Upwork summer 2025 release on Uma AI work agent."
  },
  {
    tier: "Tier 3",
    track: "A1 Agent platforms / agent builders",
    company: "Lindy",
    website: "https://www.lindy.ai",
    fitReason: "Lindy sits close to the workflow edge where SMB agents may soon need real money movement or buying actions.",
    insertion: "SMB assistant workflows that escalate from coordination into subscriptions, software, or vendor actions.",
    teamBuyer: "Product, platform, partnerships.",
    whyNow: "Growing demand for SMB workflow agents makes a safer payment-action layer increasingly relevant.",
    fit: 7,
    confidence: 6,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Strong fit as a workflow-agent company likely to explore action-heavy use cases."
  },
  {
    tier: "Tier 3",
    track: "A1 Agent platforms / agent builders",
    company: "Bardeen",
    website: "https://www.bardeen.ai",
    fitReason: "Automation agents already live in operational workflows that could grow into spend or procurement tasks.",
    insertion: "Go-to-market and back-office agents that need bounded purchasing or vendor interactions.",
    teamBuyer: "Product, automation platform, partnerships.",
    whyNow: "Operational automation agents keep broadening from task automation into workflow execution.",
    fit: 7,
    confidence: 6,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Strong automation-agent adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Fiverr",
    website: "https://www.fiverr.com",
    fitReason: "Marketplace plus AI-native matching and creator tools make Fiverr relevant as work becomes more agent-mediated.",
    insertion: "Buyer-side hiring and purchase flows where AI can recommend, match, and potentially trigger spend.",
    teamBuyer: "AI platform, marketplace product, payments, growth.",
    whyNow: "Fiverr launched Fiverr Go, is talking about an agentic economy, and sees major demand for AI-agent services.",
    fit: 6,
    confidence: 7,
    reachability: 7,
    personalization: 8,
    pilot: 7,
    signal: "Fiverr Go launch, AI matching, and business trends index around AI agents."
  },
  {
    tier: "Tier 3",
    track: "A1 Agent platforms / agent builders",
    company: "Airtop",
    website: "https://www.airtop.ai",
    fitReason: "Browser and web-automation agents will increasingly need safe economic actions, not just page interaction.",
    insertion: "Automated web workflows that require buying, booking, or paying for services during execution.",
    teamBuyer: "Product, platform, developer partnerships.",
    whyNow: "The browser-agent stack is moving quickly toward end-to-end task completion, including commercial actions.",
    fit: 8,
    confidence: 7,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Strong browser-agent adjacency similar to Browserbase, though with less public payment evidence."
  },
  {
    tier: "Tier 3",
    track: "A1 Agent platforms / agent builders",
    company: "Gumloop",
    website: "https://www.gumloop.com",
    fitReason: "No-code AI workflow automation could make Sardis a safe payment action for non-technical builders.",
    insertion: "User-built agents that need bounded payments, API purchases, or procurement steps.",
    teamBuyer: "Product, platform, partnerships.",
    whyNow: "The no-code agent market is maturing toward more ambitious business workflows.",
    fit: 7,
    confidence: 6,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Clear fit with no-code agent execution and business workflows."
  },
  {
    tier: "Tier 3",
    track: "A1 Agent platforms / agent builders",
    company: "AirOps",
    website: "https://www.airops.com",
    fitReason: "Agentic workflow builders used by GTM teams may eventually need controlled spend or data-buying actions.",
    insertion: "Marketing, research, or RevOps agents that purchase tools, data, or services.",
    teamBuyer: "Platform, product, AI workflows.",
    whyNow: "As GTM agents become more autonomous, purchasing and API-spend controls become a practical next step.",
    fit: 6,
    confidence: 6,
    reachability: 8,
    personalization: 7,
    pilot: 7,
    signal: "GTM-agent positioning and workflow-adjacency."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Uber",
    website: "https://www.uber.com",
    fitReason: "Large marketplace with sophisticated payments and operational automation, but harder to wedge in near term.",
    insertion: "Internal ops agents, merchant and driver support, or procurement workflows with bounded spend.",
    teamBuyer: "Marketplace ops, AI/automation, payments product.",
    whyNow: "Strategically relevant as mobility and delivery workflows become more automated, though reach and pilot odds are lower.",
    fit: 6,
    confidence: 6,
    reachability: 4,
    personalization: 8,
    pilot: 4,
    signal: "Massive transaction volume and AI automation adjacency."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "DoorDash",
    website: "https://about.doordash.com",
    fitReason: "Commerce, logistics, and support workflows make DoorDash a plausible agentic commerce target.",
    insertion: "Refunds, merchant ops, procurement, and support agents with controlled payment actions.",
    teamBuyer: "AI/automation, marketplace product, payments.",
    whyNow: "High operational complexity and commerce adjacency make the fit real, though not immediate.",
    fit: 7,
    confidence: 7,
    reachability: 5,
    personalization: 8,
    pilot: 5,
    signal: "Marketplace, support, and high-volume transactional complexity."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Instacart",
    website: "https://www.instacart.com/company",
    fitReason: "One of the strongest commerce examples outside pure payments because ChatGPT checkout is already live here.",
    insertion: "Grocery shopping agents, consumer checkout, and merchant-side order/payment workflows.",
    teamBuyer: "Shopping product, payments, AI product, partnerships.",
    whyNow: "Instacart and OpenAI launched an integrated grocery checkout experience inside ChatGPT in late 2025.",
    fit: 8,
    confidence: 9,
    reachability: 6,
    personalization: 9,
    pilot: 7,
    signal: "OpenAI partnership announcement for Instacart app and checkout in ChatGPT."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Airbnb",
    website: "https://www.airbnb.com",
    fitReason: "Travel and payments complexity is high, but evidence of near-term agentic payment experimentation is thinner.",
    insertion: "Travel booking and support flows where AI might handle modifications, refunds, or purchase decisions.",
    teamBuyer: "Marketplace product, AI, payments, guest support.",
    whyNow: "Relevant logo target, but weaker near-term fit than corporate travel or procurement players.",
    fit: 6,
    confidence: 6,
    reachability: 5,
    personalization: 7,
    pilot: 4,
    signal: "Travel-commerce adjacency with future AI-shopping relevance."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Booking Holdings",
    website: "https://www.bookingholdings.com",
    fitReason: "Travel commerce and payment orchestration are relevant, but direct public agent-payment evidence is still lighter.",
    insertion: "Travel booking, refunds, and service agents where approvals or spend controls may matter.",
    teamBuyer: "Payments, travel product, AI/automation leadership.",
    whyNow: "Travel remains one of the most credible agentic-booking categories, but public signal depth is moderate.",
    fit: 6,
    confidence: 6,
    reachability: 4,
    personalization: 7,
    pilot: 4,
    signal: "Strong travel-commerce adjacency."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Expedia Group",
    website: "https://www.expediagroup.com",
    fitReason: "Transaction-heavy travel flows make Expedia plausible, especially if AI booking agents grow.",
    insertion: "Trip booking, refunds, support, and partner settlement workflows with agent assistance.",
    teamBuyer: "Payments, travel product, AI/ML, marketplace operations.",
    whyNow: "Good category fit, but less immediate than Navan, TravelPerk, or Priceline.",
    fit: 6,
    confidence: 6,
    reachability: 5,
    personalization: 7,
    pilot: 5,
    signal: "Travel booking and payment complexity."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Gusto",
    website: "https://gusto.com",
    fitReason: "Payroll and SMB finance workflows could benefit from bounded payment automation over time.",
    insertion: "Payroll ops, reimbursements, and finance agents that may trigger payments under policy.",
    teamBuyer: "Product, payroll platform, finance automation.",
    whyNow: "A plausible mid-market pilot target if AI starts taking more operational actions inside SMB finance.",
    fit: 6,
    confidence: 6,
    reachability: 7,
    personalization: 6,
    pilot: 6,
    signal: "Payroll/finance ops adjacency."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Walmart",
    website: "https://corporate.walmart.com",
    fitReason: "Massive commerce scale makes it strategically relevant, but reachability and near-term pilot odds are low.",
    insertion: "Shopping, supplier, and internal procurement agents with tightly bounded commercial actions.",
    teamBuyer: "Commerce AI, marketplace product, procurement innovation.",
    whyNow: "Large logo and strong long-term relevance, but not a fast-learn pilot target.",
    fit: 6,
    confidence: 6,
    reachability: 4,
    personalization: 8,
    pilot: 3,
    signal: "Scale and commerce complexity, but weak near-term access."
  },
  {
    tier: "Tier 3",
    track: "A2 Internal enterprise AI & automation teams",
    company: "Target",
    website: "https://corporate.target.com",
    fitReason: "Retail and commerce make the strategic fit real, but the near-term wedge is less obvious than with commerce platforms.",
    insertion: "Shopping, order, and procurement agents that eventually need payment guardrails.",
    teamBuyer: "Digital product, AI/ML, payments, procurement innovation.",
    whyNow: "Worth tracking for later-stage commerce outreach, not for first-wave pilots.",
    fit: 6,
    confidence: 5,
    reachability: 4,
    personalization: 7,
    pilot: 3,
    signal: "Large commerce operator with long-term relevance."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Visa",
    website: "https://www.visa.com",
    fitReason: "Strategically important for agentic commerce standards and delegated credentialing, though hard to access.",
    insertion: "Network-level controls, merchant trust, tokenization, and delegated payment authorizations for agents.",
    teamBuyer: "Innovation, digital commerce, partnerships.",
    whyNow: "Appears repeatedly in agentic-commerce ecosystem announcements, including Checkout.com and Spreedly discussions.",
    fit: 8,
    confidence: 8,
    reachability: 3,
    personalization: 9,
    pilot: 4,
    signal: "Referenced in multiple agentic-commerce and open-payments ecosystem announcements."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Mastercard",
    website: "https://www.mastercard.com",
    fitReason: "Also strategically important for agentic payment standards, but harder to convert into a near-term pilot.",
    insertion: "Credential frameworks, delegated approval, and network-side controls for agent transactions.",
    teamBuyer: "Innovation, digital commerce, product partnerships.",
    whyNow: "Mastercard is part of the agentic-commerce standards conversation, but likely a longer-cycle effort.",
    fit: 8,
    confidence: 8,
    reachability: 3,
    personalization: 9,
    pilot: 4,
    signal: "Frequently referenced in protocol and agentic-commerce ecosystem work."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Rapyd",
    website: "https://www.rapyd.net",
    fitReason: "Strong cross-border and compliance narrative makes Rapyd a plausible control-layer target.",
    insertion: "AI-optimized auth, fraud, and compliance workflows where agent-led payment decisions need guardrails.",
    teamBuyer: "Payments, compliance, product, orchestration.",
    whyNow: "Rapyd is publishing heavily on AI in payments, compliance, and agentic commerce themes.",
    fit: 7,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 6,
    signal: "Rapyd’s AI-and-payments series and cross-border positioning."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "dLocal",
    website: "https://www.dlocal.com",
    fitReason: "Emerging-market payments and recurring methods make dLocal relevant for global agentic commerce expansion.",
    insertion: "Localized payment controls for recurring or cross-border agent-led commerce in high-growth markets.",
    teamBuyer: "Product, local methods, merchant growth, partnerships.",
    whyNow: "Pix Automático and recurring local methods create new surfaces for delegated, policy-aware payment flows.",
    fit: 7,
    confidence: 7,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "dLocal content on Pix Automático and recurring payment modernization."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "MoonPay",
    website: "https://www.moonpay.com",
    fitReason: "Crypto-to-fiat and onboarding layers could benefit from safer agent-controlled wallet or purchase actions.",
    insertion: "Onramp, wallet, and agent purchase flows that need thresholds and compliance evidence.",
    teamBuyer: "Product, wallet/onramp, partnerships.",
    whyNow: "Broader stablecoin and consumer crypto infrastructure gives MoonPay some plausible agentic-commerce relevance.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Strong stablecoin/consumer wallet adjacency."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Paddle",
    website: "https://www.paddle.com",
    fitReason: "Merchant-of-record infrastructure is relevant if agentic commerce expands quickly for software and subscriptions.",
    insertion: "Digital-goods, SaaS, and subscription agents that trigger purchases or billing changes.",
    teamBuyer: "Product, billing, merchant solutions.",
    whyNow: "Useful as a digital-goods angle even though direct agentic payment evidence is still modest.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 6,
    signal: "Strong MoR adjacency for digital goods and SaaS."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "FastSpring",
    website: "https://fastspring.com",
    fitReason: "Similar to Paddle, but positioned around software commerce and merchant-of-record needs.",
    insertion: "AI-mediated digital product purchases, subscriptions, and tax/compliance-aware billing flows.",
    teamBuyer: "Product, billing, commerce platform.",
    whyNow: "Relevant for the digital goods track, though weaker than platforms already public on agentic commerce.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 6,
    pilot: 6,
    signal: "Digital-goods merchant-of-record adjacency."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "EBANX",
    website: "https://www.ebanx.com",
    fitReason: "Cross-border commerce in LATAM plus orchestration partnerships make EBANX a credible regional expansion target.",
    insertion: "Localized pay-in flows where agent-led commerce needs market-specific payment controls and routing.",
    teamBuyer: "Product, regional partnerships, enterprise merchants.",
    whyNow: "EBANX appears in orchestration ecosystem announcements and benefits from agentic commerce spreading globally.",
    fit: 7,
    confidence: 7,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Spreedly partnership and LATAM commerce positioning."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Payoneer",
    website: "https://www.payoneer.com",
    fitReason: "Cross-border payouts and marketplace commerce make Payoneer a plausible but broader-fit target.",
    insertion: "B2B payouts, supplier payments, and marketplace settlement agents with approval logic.",
    teamBuyer: "Product, B2B payments, marketplace partnerships.",
    whyNow: "Reasonable cross-border fit, but public agentic-commerce evidence is weaker than top-tier payment targets.",
    fit: 6,
    confidence: 6,
    reachability: 6,
    personalization: 7,
    pilot: 5,
    signal: "Cross-border payout and marketplace adjacency."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "Worldpay",
    website: "https://www.worldpay.com",
    fitReason: "Global merchant footprint makes it strategically relevant, though likely slower-moving and harder to wedge.",
    insertion: "Agent-initiated enterprise merchant checkout with external policy and risk layers.",
    teamBuyer: "Enterprise commerce, partnerships, innovation.",
    whyNow: "Important long-cycle enterprise payments logo, not a first-wave pilot target.",
    fit: 6,
    confidence: 6,
    reachability: 4,
    personalization: 7,
    pilot: 4,
    signal: "Enterprise merchant processing scale."
  },
  {
    tier: "Tier 3",
    track: "A3 Fintech / commerce / payment design partners",
    company: "ACI Worldwide",
    website: "https://www.aciworldwide.com",
    fitReason: "Legacy payments infrastructure gives strategic relevance, but near-term fit is weaker than modern API-first players.",
    insertion: "Enterprise payment routing and fraud layers for agentic commerce experiments.",
    teamBuyer: "Product strategy, enterprise payments, innovation.",
    whyNow: "Useful as a long-cycle enterprise target, not an immediate pilot lead.",
    fit: 6,
    confidence: 5,
    reachability: 4,
    personalization: 6,
    pilot: 4,
    signal: "Broad enterprise payments infrastructure adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Priceline",
    website: "https://www.priceline.com",
    fitReason: "Spreedly explicitly cites Priceline as testing AI-driven payment experiences, which makes this a strong travel target.",
    insertion: "AI booking and checkout flows for travel purchases where spend rules and merchant controls matter.",
    teamBuyer: "Payments, travel checkout, AI product.",
    whyNow: "Priceline is one of the clearest public examples of live AI-driven travel payment experimentation.",
    fit: 8,
    confidence: 8,
    reachability: 6,
    personalization: 8,
    pilot: 7,
    signal: "Spreedly’s March 2026 agentic commerce launch cites Priceline."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Hopper",
    website: "https://hopper.com",
    fitReason: "Hopper already sits at the intersection of travel, fintech, insurance, and automated decisioning.",
    insertion: "Travel purchase and price-lock flows where agent decisions need bounded payment execution.",
    teamBuyer: "Product, payments, travel fintech, AI.",
    whyNow: "Good category fit for agentic travel booking, though public payment-control signals are lighter than Navan or Priceline.",
    fit: 7,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 7,
    signal: "Travel fintech and booking automation adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Coupa",
    website: "https://www.coupa.com",
    fitReason: "Enterprise procurement and spend management is one of Sardis’s most intuitive expansion tracks.",
    insertion: "Supplier review, approvals, and payment-release workflows with agent assistance.",
    teamBuyer: "Procurement, spend management, AI product.",
    whyNow: "Procurement teams are adopting AI quickly, and Coupa has the spend-control context that Sardis can deepen.",
    fit: 7,
    confidence: 7,
    reachability: 6,
    personalization: 7,
    pilot: 6,
    signal: "Procurement AI adoption trend and direct spend-management adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Amadeus",
    website: "https://amadeus.com",
    fitReason: "Travel infrastructure provider with many downstream transaction points, but slower-moving and harder to reach.",
    insertion: "Travel distribution and booking flows where agent commerce could introduce new payment-control requirements.",
    teamBuyer: "Payments, travel tech partnerships, innovation.",
    whyNow: "Travel infrastructure is strategically relevant as AI booking agents mature, though pilot velocity may be modest.",
    fit: 7,
    confidence: 6,
    reachability: 5,
    personalization: 7,
    pilot: 5,
    signal: "Travel infrastructure adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Sabre",
    website: "https://www.sabre.com",
    fitReason: "Similar to Amadeus, with strong travel-distribution relevance but weaker near-term agility.",
    insertion: "Agent-driven itinerary and booking flows with payment authorization controls.",
    teamBuyer: "Product innovation, travel distribution, payments.",
    whyNow: "Good strategic fit for travel-agent commerce, but likely a longer sales cycle.",
    fit: 7,
    confidence: 6,
    reachability: 5,
    personalization: 7,
    pilot: 5,
    signal: "Travel infrastructure adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Vendr",
    website: "https://www.vendr.com",
    fitReason: "Software procurement is an obvious use case for agents that need to compare, recommend, and commit spend safely.",
    insertion: "Renewal, buying, and vendor-comparison agents with bounded authority over software purchases.",
    teamBuyer: "Procurement platform, product, AI/automation.",
    whyNow: "Excellent design-partner candidate because software procurement is structured, painful, and payment-adjacent.",
    fit: 7,
    confidence: 6,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Software procurement adjacency and high workflow pain."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Tropic",
    website: "https://www.tropicapp.io",
    fitReason: "Same procurement pattern as Vendr, with strong fit around vendor evaluation and spend governance.",
    insertion: "Intake-to-purchase agents that need strict approval and payment boundaries.",
    teamBuyer: "Product, procurement orchestration, AI/automation.",
    whyNow: "Procurement teams are actively adopting AI and Tropic is small enough to be reachable.",
    fit: 7,
    confidence: 6,
    reachability: 8,
    personalization: 7,
    pilot: 8,
    signal: "Procurement orchestration adjacency with good reachability."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Order.co",
    website: "https://www.order.co",
    fitReason: "B2B purchasing and payables are ideal for a Sardis-like wedge because the job is literally controlled buying.",
    insertion: "PO, vendor, and purchasing agents with policy limits and approval escalation.",
    teamBuyer: "Product, procurement automation, AP automation.",
    whyNow: "Strong painkiller fit for autonomous purchasing under finance-approved rules.",
    fit: 7,
    confidence: 6,
    reachability: 8,
    personalization: 6,
    pilot: 8,
    signal: "Direct fit around controlled B2B purchasing."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Faire",
    website: "https://www.faire.com",
    fitReason: "B2B wholesale ordering has clear agentic-buying potential, but public evidence is lighter than top-tier targets.",
    insertion: "Retailer-side replenishment or vendor-ordering agents with bounded purchasing rules.",
    teamBuyer: "Marketplace product, payments, retailer tooling.",
    whyNow: "Interesting B2B commerce angle that could learn quickly if agents begin ordering inventory.",
    fit: 6,
    confidence: 6,
    reachability: 7,
    personalization: 7,
    pilot: 6,
    signal: "B2B ordering and marketplace adjacency."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Etsy",
    website: "https://www.etsy.com",
    fitReason: "Already live with ChatGPT shopping and checkout, making it one of the most concrete commerce targets in the market.",
    insertion: "Marketplace checkout, seller protection, and agent-aware merchant controls for AI shopping.",
    teamBuyer: "Marketplace product, payments, AI commerce, trust & safety.",
    whyNow: "OpenAI and Etsy are already live on in-chat buying, so the next problem is trust, policy, and control.",
    fit: 8,
    confidence: 9,
    reachability: 6,
    personalization: 9,
    pilot: 7,
    signal: "Etsy’s official post on AI-powered shopping with OpenAI and direct in-chat checkout."
  },
  {
    tier: "Tier 3",
    track: "A4 Procurement / travel / marketplace operators",
    company: "Amazon Business",
    website: "https://business.amazon.com",
    fitReason: "Procurement scale is enormous, but the account-level reachability and pilot likelihood are low.",
    insertion: "Business buying agents, catalog ordering, and procurement policy enforcement.",
    teamBuyer: "Amazon Business product, procurement tech, AI innovation.",
    whyNow: "Strategically important if agentic procurement accelerates, but not an efficient early outbound target.",
    fit: 7,
    confidence: 6,
    reachability: 2,
    personalization: 8,
    pilot: 2,
    signal: "Massive procurement adjacency with low access."
  }
];

const outDir = join(process.cwd(), "docs", "outbound");
mkdirSync(outDir, { recursive: true });

const scoringNote = [
  "# Phase 2 Target Universe",
  "",
  "Date: 2026-03-10",
  "",
  "Tracks:",
  "- A1: Agent platforms / agent builders",
  "- A2: Internal enterprise AI & automation teams",
  "- A3: Fintech / commerce / payment design partners",
  "- A4: Procurement / travel / marketplace operators",
  "",
  "Scores:",
  "- Fit: direct product-to-workflow fit",
  "- Confidence: evidence quality behind the fit hypothesis",
  "- Reach: realistic access to a relevant decision-maker or champion",
  "- Pers: public context available for meaningful personalization",
  "- Pilot: near-term probability of a design-partner or pilot conversation",
  "",
  `Track distribution: A1 ${targets.filter((t) => t.track.startsWith("A1")).length}, A2 ${targets.filter((t) => t.track.startsWith("A2")).length}, A3 ${targets.filter((t) => t.track.startsWith("A3")).length}, A4 ${targets.filter((t) => t.track.startsWith("A4")).length}.`,
  ""
];

function renderTable(rows) {
  const header = [
    "| Company | Track | Why fit + insertion point | Likely team / buyer | Why now | Scores |",
    "| --- | --- | --- | --- | --- | --- |"
  ];
  const body = rows.map((t) => {
    const fitText = `${t.fitReason} ${t.insertion}`;
    const scores = `${t.fit}/${t.confidence}/${t.reachability}/${t.personalization}/${t.pilot}`;
    return `| [${t.company}](${t.website}) | ${t.track.replace(/^A\\d\\s+/, "")} | ${fitText} | ${t.teamBuyer} | ${t.whyNow} | ${scores} |`;
  });
  return header.concat(body).join("\n");
}

const mdParts = [...scoringNote];
for (const tier of ["Tier 1", "Tier 2", "Tier 3"]) {
  mdParts.push(`## ${tier}`);
  mdParts.push("");
  mdParts.push(renderTable(targets.filter((t) => t.tier === tier)));
  mdParts.push("");
}

const mdPath = join(outDir, "phase2-target-universe-2026-03-10.md");
writeFileSync(mdPath, mdParts.join("\n"));

const csvHeader = [
  "tier",
  "track",
  "company",
  "website",
  "fit_reason",
  "workflow_insertion_point",
  "likely_team_buyer",
  "why_now",
  "fit_score",
  "confidence_score",
  "reachability_score",
  "personalization_richness_score",
  "pilot_likelihood_score",
  "public_signal_note"
];

function csvEscape(value) {
  const text = String(value ?? "");
  return `"${text.replaceAll('"', '""')}"`;
}

const csvLines = [csvHeader.join(",")];
for (const t of targets) {
  csvLines.push(
    [
      t.tier,
      t.track,
      t.company,
      t.website,
      t.fitReason,
      t.insertion,
      t.teamBuyer,
      t.whyNow,
      t.fit,
      t.confidence,
      t.reachability,
      t.personalization,
      t.pilot,
      t.signal
    ]
      .map(csvEscape)
      .join(",")
  );
}

const csvPath = join(outDir, "phase2-target-universe-2026-03-10.csv");
writeFileSync(csvPath, csvLines.join("\n"));

console.log(`wrote ${targets.length} targets`);
console.log(mdPath);
console.log(csvPath);
